apiVersion: opentofu.upbound.io/v1beta1
kind: Workspace
metadata:
  name: azure-sb-u08kdt7fct1-1762729084
  namespace: azure-sandboxes
  annotations:
    crossplane.io/external-name: azure-sb-u08kdt7fct1-1762729084
  labels:
    app.kubernetes.io/managed-by: github-actions
    provisioned-by: slack-bot
    slack-user-id: U08KDT7FCT1
    request-id: 6ebe5a7a-fb9f-4f72-abb4-f30eb82f5159
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/OasisSecurity/Solutions-Architecture
    entrypoint: Labs/Azure/src
    
    env:
      - name: ARM_SUBSCRIPTION_ID
        secretKeyRef:
          namespace: azure-sandboxes
          name: azure-sb-u08kdt7fct1-1762729084-credentials
          key: ARM_SUBSCRIPTION_ID
      - name: ARM_TENANT_ID
        secretKeyRef:
          namespace: azure-sandboxes
          name: azure-sb-u08kdt7fct1-1762729084-credentials
          key: ARM_TENANT_ID
      - name: ARM_CLIENT_ID
        secretKeyRef:
          namespace: azure-sandboxes
          name: azure-sb-u08kdt7fct1-1762729084-credentials
          key: ARM_CLIENT_ID
      - name: ARM_CLIENT_SECRET
        secretKeyRef:
          namespace: azure-sandboxes
          name: azure-sb-u08kdt7fct1-1762729084-credentials
          key: ARM_CLIENT_SECRET
      - name: TF_VAR_subscription_id
        secretKeyRef:
          namespace: azure-sandboxes
          name: azure-sb-u08kdt7fct1-1762729084-credentials
          key: subscription_id
      - name: TF_VAR_tenant_id
        secretKeyRef:
          namespace: azure-sandboxes
          name: azure-sb-u08kdt7fct1-1762729084-credentials
          key: tenant_id
      - name: TF_VAR_client_id
        secretKeyRef:
          namespace: azure-sandboxes
          name: azure-sb-u08kdt7fct1-1762729084-credentials
          key: client_id
      - name: TF_VAR_location
        value: "East US"
  
  writeConnectionSecretToRef:
    namespace: azure-sandboxes
    name: azure-sb-u08kdt7fct1-1762729084-outputs
